name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --build-arg "NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}" --build-arg "SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" --build-arg "SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}" --build-arg "supabaseUrl=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}" --build-arg "VALKEY_HOST=${{ secrets.VALKEY_HOST }}" --build-arg "VALKEY_PORT=${{ secrets.VALKEY_PORT }}" --build-arg "VALKEY_PASSWORD=${{ secrets.VALKEY_PASSWORD }}" --tag my-image-name:latest
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - name: Tag the Docker image
        run: docker tag my-image-name:latest ${{ secrets.DOCKERHUB_USERNAME }}/my-image-name:latest
      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-image-name:latest
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          envs: NEXT_PUBLIC_SUPABASE_URL,SUPABASE_SERVICE_ROLE_KEY,SUPABASE_URL,VALKEY_HOST,VALKEY_PORT,VALKEY_PASSWORD,DOCKERHUB_USERNAME
          script: |
            cd /root/build-route-api # or your actual project path
            export NEXT_PUBLIC_SUPABASE_URL="${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}"
            export SUPABASE_SERVICE_ROLE_KEY="${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}"
            export SUPABASE_URL="${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}"
            export VALKEY_HOST="${{ secrets.VALKEY_HOST }}"
            export VALKEY_PORT="${{ secrets.VALKEY_PORT }}"
            export VALKEY_PASSWORD="${{ secrets.VALKEY_PASSWORD }}"
            export DOCKERHUB_USERNAME="${{ secrets.DOCKERHUB_USERNAME }}"
            ./deploy.sh 