name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run Docker container
    - run: |
        docker run -e NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }} \
               -e SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }} \
               -e VALKEY_HOST=${{ secrets.VALKEY_HOST }} \
               -e VALKEY_PORT=${{ secrets.VALKEY_PORT }} \
               -e VALKEY_PASSWORD=${{ secrets.VALKEY_PASSWORD }} \
               -p 3000:3000 my-image-name:$(date +%s)
